name: Validate tap

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tap repo
        run: brew tap erighetto/homebrew-aws-session-manager-plugin "$GITHUB_WORKSPACE"

      - name: Brew style
        run: brew style Casks/session-manager-plugin.rb

      - name: Brew audit
        run: brew audit --cask session-manager-plugin
